services:
  hackbet:
    build: .
    container_name: hackbet
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=cambia-este-secreto-en-produccion
      - ADMIN_USERNAME=PabloR-ADMIN
      - ADMIN_PASSWORD=T3stP4ss!
      - DB_PATH=/app/data/hackbet.db
    volumes:
      - hackbet_data:/app/data
    restart: unless-stopped

volumes:
  hackbet_data:
